

POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "nome": "Otto",
  "cpf": "10171080483",
  "email": "otto@email.com",
  "telefone": "83998362522",
  "senha": "123123"
}

###
POST localhost:8080/auth/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJsb2dpbi1hdXRoLWFwaSIsInN1YiI6Im90dG9AZW1haWwuY29tIiwiZXhwIjoxNzQzNDQzNjgyfQ.O8SilPaT61F4e4cZCyd93zOEHevbWSJHVdixds9cr4A"

{
  "email": "otto@email.com",
  "senha": "123123"
}
